{% set name = "aws-c-s3" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b8350a10050015493345453167d619f1b407c4970fa3fe5aaaf2b42ab93b7b6b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-s3", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake
    - ninja-base
  host:
    - aws-checksums 0.2.8
    - aws-c-auth 0.9.4
    - aws-c-cal 0.9.13
    - aws-c-common 0.12.6
    - aws-c-http 0.10.7
    - aws-c-io 0.23.3
    - openssl {{ openssl }}  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-s3${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/s3/s3.h  # [unix]
    - if not exist %LIBRARY_INC%\aws\s3\s3.h exit 1 # [win]
    - if not exist %LIBRARY_BIN%\aws-c-s3.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-s3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 library implementation for communicating with the S3 service.
  description: |
    The AWS-C-S3 library is an asynchronous AWS S3 client focused on maximizing throughput and network utilization.
  doc_url: https://github.com/awslabs/aws-c-s3
  dev_url: https://github.com/awslabs/aws-c-s3

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
